// lib/mockData.ts
import type { Deal } from '@/types/deals';

export const MOCK_DEALS: Deal[] = [
  {
    id: '1',
    stage: 'RESEARCHING',
    opportunityName: 'Shared ledger for secondary funds',
    investorName: 'Akili Mensah',
    firmName: 'Polaris West',
    amountTarget: 400000,
    lastInteractionAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Nina (Platform)',
    priority: 'High',
    thesisArea: 'Fintech infra',
    source: 'VC peer referral',
    notes: 'Strong founder-market fit; ask for product screenshots before intro.',
  },
  {
    id: '2',
    stage: 'OUTREACHED',
    opportunityName: 'Seed round for InfraCo',
    investorName: 'Alex Chen',
    firmName: 'Latitude Ventures',
    amountTarget: 1500000,
    nextFollowUpAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Sam (Partner)',
    priority: 'Medium',
    thesisArea: 'Dev tooling',
    source: 'Outbound',
    notes: 'Replied with product demo link; wants partner meeting after LAUNCH announcement.',
  },
  {
    id: '3',
    stage: 'IN_CONVERSATION',
    opportunityName: 'Pre-seed for SocialGraph',
    investorName: 'Maria Lopez',
    firmName: 'Signal Peak',
    amountTarget: 500000,
    nextFollowUpAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Jess (Associate)',
    priority: 'High',
    thesisArea: 'AI x productivity',
    source: 'Founder referral',
    notes: 'Scheduling founder coffee; ask for deck refresh with AI roadmap.',
  },
  {
    id: '4',
    stage: 'WARM_INTRO_NEEDED',
    opportunityName: 'AI co-pilot for oncology labs',
    investorName: 'Dr. Emily Zhang',
    firmName: 'Atrium Ventures',
    amountTarget: 2200000,
    nextFollowUpAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Sam (Partner)',
    priority: 'High',
    thesisArea: 'Applied AI / Bio',
    source: 'Angel syndicate',
    notes: 'Need intro from mutual LP; highlight diagnostics distribution.',
  },
  {
    id: '5',
    stage: 'PASSED',
    opportunityName: 'Marketplace for remote nursing shifts',
    investorName: 'Leo Martinez',
    firmName: 'CareBridge',
    amountTarget: 850000,
    lastInteractionAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Nina (Platform)',
    priority: 'Low',
    thesisArea: 'Healthcare ops',
    source: 'Inbound',
    notes: 'Passed due to CAC/LTV clarity; keep in newsletter for future updates.',
  },
  {
    id: '6',
    stage: 'INVESTED',
    opportunityName: 'Quant infra for climate risk',
    investorName: 'Olivia Reed',
    firmName: 'Pioneer Labs',
    amountTarget: 3000000,
    lastInteractionAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Sam (Partner)',
    priority: 'Medium',
    thesisArea: 'Climate / infra',
    source: 'Warm intro',
    notes: 'Closing onboarding tasks; invite to portfolio founder slack.',
  },
  {
    id: '7',
    stage: 'RESEARCHING',
    opportunityName: 'Data room automation for LatAm funds',
    investorName: 'Valentina Ruiz',
    firmName: 'Andina Capital',
    amountTarget: 600000,
    nextFollowUpAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    owner: 'Jess (Associate)',
    priority: 'Medium',
    thesisArea: 'Workflow automation',
    source: 'VC peer referral',
    notes: 'Building MVP with two design partners; wants intro to GTM advisor.',
  },
];
